server:
  port: 0

spring:
  application:
    name: AuditService
  config:
    import: "optional:configserver:"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8762/eureka}