server:
  port: 0

spring:
  application:
    name: audit-service
  profiles:
    active: dev
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true


#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/audit-service
#    username: postgres
#    password: postgres
#
#  jpa:
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        format_sql: true
#    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8762/eureka}