server:
  port: 8765

spring:
  application:
    name: gateway-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8762/eureka}
    enabled: true
    eureka-service-url-poll-interval-seconds: 30
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30

