spring:
  application:
    name: audit-service
  datasource:
    url: jdbc:postgresql://localhost:5432/audit-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

