server:
  port: 0

spring:
  application:
    name: auth-service
  profiles:
    active: dev
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8762/eureka}

jwt:
  access:
    secret: ${JWT_ACCESS_SECRET:3j6TZzKfFjZGBqBqrbLB6FUpaj7OEfCsSydwiTgf2eDx1bd9dWOBbZTDvdDBrfY}
    expiration: ${JWT_ACCESS_EXPIRATION:300}
  refresh:
    secret: ${JWT_REFRESH_SECRET:chCGDeS4wSzG64uTKwlBlTvvbvkmj09Mr14emIg6XvTeqaZiT1laXPXkFj4yVYO}
    expiration: ${JWT_REFRESH_EXPIRATION:3600}

redis:
  host: localhost
  port: 6379
  password: redis
  cache:
    prefix:
      block-refresh-token: refresh-token-block/
      block-access-token: access-token-block/
    users-cache-expiration: 600