server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: dev
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: https://github.com/Homval/ConfigRepository.git
          searchPaths: "/ms-config-files/{application}/{profile}"
          default-label: main
          clone-on-start: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8762/eureka}
