server:
  port: 8088

spring:
  application:
    name: ConfigService
  profiles:
    active: dev
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: https://github.com/Homval/MSDeliveryDemo
          searchPaths: "/ms-configs-properties/{application}/{profile}"
          default-label: main

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8762/eureka}
